# Generated by Django 4.1.7 on 2023-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(
                help_text="A label name.", max_length=255, verbose_name="Name"
            ),
        ),
    ]
